### ISSUE TITLE
Use compliant mode when pushing on the table

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/superquadric-grasp#5]
The use of `compliant mode` is necessary in order to avoid the robot to be push on the table if the desired pose is too close to it.

**Comment by pattacini** [comment]
The use of compliance is definitely desirable 👍 

In addition, take into account these considerations:
- A compliant limb tends to suffer from larger errors while reaching, but we have visual-servoing to compensate for that.
- I'd use also the `wholeBodyDynamics` measurements of the force exchanged at the end-effector as a guard for a hard stop.

**Comment by giuliavezzani** [comment]
Update:
- `wholeBodyDynamics` measurements of forces are used for stopping the `cartesianController` or the `visual-servoing` while pushing againt an obstacle or a table. :white_check_mark: 
- `compliant mode` option is available and has been tested **without** the `visual servoing`:white_check_mark:

To do:
- test the `compliant mode` **with** the `visual servoing`

**Comment by giuliavezzani** [comment]
I didn't close this issue since I didn't test `compliant mode` while using `visual servoing`. Did you?
In the "standard" demo, we measure the forces but the joints are still controlled in `stiff mode`.

**Comment by pattacini** [comment]
Not tested yet, let's keep this close anyway.
We will get back to it if we'll spot any malfunctioning.
👍
